### ISSUE TITLE
[CAD] - add a tensioning screw to the Z-Side of the Y-gantry.

### ISSUE THREAD

**Issue by cad435** [index-machines/index#117]
Right now the tension is only applied from one side, that will bend the lower V-slot wheel. Step-file attached (please note that the attached step file is also thinner, as I modified this for my personal needs!)
![unknown](https://user-images.githubusercontent.com/16453385/106174037-e6ca3e00-6194-11eb-822d-651f524d6be6.png)
[Issue output v1.zip](https://github.com/sphawes/index/files/5888909/Issue.output.v1.zip)

**Comment by G-Pereira** [comment]
This is rather a dirty fix cad435! :D Do you have any other suggestion to this? (most probably with changes to the Z rail)

**Comment by cad435** [comment]
Actually no.
This is placed so it does not interfere with anything and the screw is aligned so.it would make contact with the bolt over the whole slot.

I use this technique often, But I'm open to other approaches!

**Comment by vysocan** [comment]
Hi @cad435, when I open your file in FreeCAD, I see a bit crippled, that is with mission holes and slots for M5 nuts. Please, any idea what do I do wrong?

**Comment by cad435** [comment]
Just opened FreeCAD and loaded the step into it:
![image](https://user-images.githubusercontent.com/16453385/111043999-395e7180-8446-11eb-8872-7a81f8321d28.png)
Can you please make a picture how its looking for you? What exactly do You mean with "a bit crippled"?

**Comment by vysocan** [comment]
I have linux FreeCAD 0.18.4:
![Screenshot_20210314_103837](https://user-images.githubusercontent.com/6968743/111063955-bffc6880-84b1-11eb-8e3d-a8c4621dd9ff.png)
![Screenshot_20210314_103907](https://user-images.githubusercontent.com/6968743/111063959-c2f75900-84b1-11eb-9648-0f40ea3d52ef.png)

**Comment by cad435** [comment]
Ah wait, you talking about the covered holes?

Yes, that's intentional. Look at the placement of the plugs, it is where the Cylindrical diameter gets smaller. That way a 3D printer would print one solid layer and the small diameter on top of that layer. After printing you can just bore it out.

It usually comes out way cleaner than without

**Comment by vysocan** [comment]
OK, thank you for clarifying. I've sliced it, to see it's truly just one layer. Just misunderstand the purpose. I thought I can drill it anyway, but also thought I can ask.
Thanks Adam.

**Comment by cad435** [comment]
No problem :)

**Comment by vysocan** [comment]
@cad435 I've printed it out. Wondering how to insert the 3rd spacer?

**Comment by cad435** [comment]
wait, I just realized that this is the X-Gantry, not the Y-Gantry...

well, yeah than you unfortunately can't use it...

**Comment by vysocan** [comment]
OK, then how about making it actually thicker? That would allow the tension screw to be hidden in the body.

**Comment by vysocan** [comment]
@cad435 I wonder something like this would work, and print?
![image](https://user-images.githubusercontent.com/6968743/111867199-cc316b80-8972-11eb-83f1-3a388f1540f1.png)
My CAD knowledge is really on beginning.

**Comment by cad435** [comment]
I would make a 0 shaped lip around that tension screw instead of making the whole part thicker.

This acts like a standoff and a printed 1mm spacer can be used so the V-Slot wheel can rotate freely...

If I manage to do this real quick this afternoon I'll post it

**Comment by vysocan** [comment]
I did not make it thicker actually. I just used the original part, and applied your tension mechanism.

**Comment by cad435** [comment]
![image](https://user-images.githubusercontent.com/16453385/111888834-68458c00-89e0-11eb-8d36-42ae4e3c0863.png)
What do you think about that? The orange part is a seperate printed part...

@G-Pereira is this worked on or still open?

**Comment by G-Pereira** [comment]
@cad435 Still open, we don't have anyone looking at it yet because we are yet to finish fixing the CAD

**Comment by vysocan** [comment]
@cad435 Looks fine to me. Is the part still thinner like your original one?
I've tried to finish my design as well, but having problem talk FreeCad into correctly create nut pocket :(.

**Comment by cad435** [comment]
errm, yes this is thiner, because I have an lasercut acrylic part laying on top of it^^

**Comment by vysocan** [comment]
I see :)

**Comment by G-Pereira** [comment]
Included in the upcoming CAD revision! Thank you!

**Comment by vysocan** [comment]
Hello @G-Pereira, forgot to mention, I come up with following:
![image](https://user-images.githubusercontent.com/6968743/118249502-c903b900-b4a5-11eb-8287-ccc9995fba29.png)
It works quite well.
Should I try to create PR or you have already some own idea.

**Comment by G-Pereira** [comment]
Hello! Check the latest video! @sphawes has already solved this issue!
