### ISSUE TITLE
[Code] Mosfet 1 Output briefly turns on after reset / power up

### ISSUE THREAD

**Issue by wilhelmzeuschner** [index-machines/index#121]
I am testing Rev. 2 and noticed that the Mosfet 1 gets turned on for 1s after power up or a reset of the MCU.
The other three mosfets don't get turned on. I have already uploaded the firmware but as far as I can tell, this is not a regular feature.

Probing the gate shows a clean signal, the pull down is in place:
![DS1Z_QuickPrint50](https://user-images.githubusercontent.com/37621765/106279671-0f0d7780-623d-11eb-9266-6af807ccf558.png)

I am not super familiar with the STM32F4, is this pin maybe used for some other function as well?
![image](https://user-images.githubusercontent.com/37621765/106280892-c5259100-623e-11eb-92b8-945c42cd9c30.png)

**Comment by G-Pereira** [comment]
Hi @wilhelmzeuschner interesting issue! At the moment I am not able to check that on my setup. Can you check the state of that pin after a reset is done?
You can use [M43](https://marlinfw.org/docs/gcode/M043.html) for that and look [here](https://github.com/stm32duino/Arduino_Core_STM32/blob/master/variants/BLACK_F407XX/variant.h) for the pin number translation

**Comment by wilhelmzeuschner** [comment]
The pin for Mosfet 1 is treated as FAN_PIN by Marlin. 
Immediately after startup:
`PIN: PC6         M42 P28          FAN_PIN                                protected`

The other mosfets are "FAN"s as well (wich makes tuning them on and off with GCODE easy):

`PIN: PD13        M42 P31          FAN3_PIN                               protected`

`PIN: PD14        M42 P30          FAN2_PIN                               protected`

`PIN: PD15        M42 P29          FAN1_PIN                               protected`


But they don't exhibit that same behavior.

After erasing the STM32s flash the pin isn't pulsed on anymore, therefore I conclude that Marlin starts the FAN0 for 1s on startup. This issue is purely software related.

**Comment by G-Pereira** [comment]
Great work @wilhelmzeuschner ! I will work on this as soon as I get my Index Mobo

**Comment by G-Pereira** [comment]
This doesn't happen anymore on REV03 but thank you!
