### ISSUE TITLE
Automation to check BOM cost difference on a suggested change for Pull Requests

### ISSUE THREAD

**Issue by G-Pereira** [index-machines/index#127]
Having the LCSC API TechWreck shared on Discord (https://lcsc.com/api/eda/product/search?keyword=LCSCPART#) we can calculate the BOM cost as part of our automation and present the price difference that a PR originates in order to help making decisions.

**Comment by daveismith** [comment]
Digikey also has one: https://developer.digikey.com/.

**Comment by sphawes** [comment]
Going to close this as we're planning on not including the price of individual parts in the BOM! (and because they're changing so rapidly nowadays)
