### ISSUE TITLE
[CAD] - back legs need cable management

### ISSUE THREAD

**Issue by daveismith** [index-machines/index#155]
The rear legs have no good mechanism to route the cables for the stepper motors back to the mobo. There should be channels or attachment points for zip ties to allow the wires to come down to the lower 2020 extrusion so the can be run back to the mobo.

**Comment by vysocan** [comment]
I wonder, may be better to hide the motors under the mount and behind the leg, then keep it stick on top?

**Comment by G-Pereira** [comment]
Fixed!
