### ISSUE TITLE
X Motor Mount set screw opening

### ISSUE THREAD

**Issue by MaeSoftGroup** [index-machines/index#158]
FDM_0006_00_x_motor_mount.stl

The set screw is covered up by the part when assembling the motor mount.  (See first pic)

I created an additional pocket for the tool to be able to reach the set screw. (See second pic)

Dan...

![IMG_6676](https://user-images.githubusercontent.com/16064379/108110558-6b580000-7061-11eb-9d44-c3b866336ed7.jpg)
![IMG_6681](https://user-images.githubusercontent.com/16064379/108110590-7579fe80-7061-11eb-9b93-e659de8e57c8.jpg)

**Comment by G-Pereira** [comment]
Thank you! This has been included in the upcoming CAD revision!
