### ISSUE TITLE
[MOBO] - Description of solder jumpers features

### ISSUE THREAD

**Issue by G-Pereira** [index-machines/index#219]
**Motherboard Revision:** REV03

**Enhancement Description:**
Make a legend of each solder jumper and tell what should be done to enable each feature. (i.e close jumper x and connect jumper y to enable USB hub LED)

**Comment by daveismith** [comment]
As we do this, we should also document the stepper motor jumper configurations.

**Comment by G-Pereira** [comment]
They are already there from rev02 actually but the fact you haven't noticed them confirms my concern that they are not easily visible

**Comment by G-Pereira** [comment]
Done!
