### ISSUE TITLE
[CAD] - Add Z-Axis idler Spacer to Repo

### ISSUE THREAD

**Issue by daveismith** [index-machines/index#221]
A spacer for the z-axis idler doesn't exist in the cad but is something a number of builders have needed to add to their builds. One was posted in discord at [https://discord.com/channels/688723670461448225/739250421893300264/796448153565790248](https://discord.com/channels/688723670461448225/739250421893300264/796448153565790248). It should be added to the git repo and assembly.

**Comment by vysocan** [comment]
Hello,
How nice. I was just collecting the z part. I've used the above cad file and created slightly modified one with nut pocket. It will allow the bolt to be firmly attached to the Y front gantry.
![image](https://user-images.githubusercontent.com/6968743/111523275-615a1780-875b-11eb-84fe-0ebb7d28a15c.png)
Also the pad is leaner to allow z gantry movement.
Actually my fist FreeCAD work :)
[Z-idler-standoff-v3.zip](https://github.com/sphawes/index/files/6159037/Z-idler-standoff-v3.zip)

**Comment by G-Pereira** [comment]
Fixed!
