### ISSUE TITLE
[FEATURE REQUEST] Make glossary definitions linkable in docs

### ISSUE THREAD

**Issue by darigovresearch** [index-machines/index#261]
Very often in glossaries for open source projects you can link to a specific definition to the glossary. Thought this would be a nice feature but unsure of how to implement this with the documentation framework being used.

This way if there is some jargon in another section of the documentation it can directly be linked to the definition in the glossary to make it easier for new joiners to understand.

**Comment by daveismith** [comment]
Check out the relative linking info: https://gohugo.io/content-management/cross-references/. I'm not quite sure how to put a custom anchor into the glossary.

**Comment by darigovresearch** [comment]
@daveismith Thanks for the guidance we'll take a look but perhaps if you put the labels `good first issue` and `help wanted` someone else may be more likely to come across it and solve the issue in a pull request before we do

**Comment by darigovresearch** [comment]
Pull request #268 attempts to add anchors to the glossary but haven't managed to figure out how to build the docs to test so feel free to test whenever you have a spare minute if they can be referenced from another page

**Comment by sphawes** [comment]
@daveismith Can I close this? Did merging #268 add this in?
