### ISSUE TITLE
[Feature request] Breakout CAN-interface and possibly add a footprint for a CAN transceiver.

### ISSUE THREAD

**Issue by Oakman-Dev** [index-machines/index#273]
I'll post this here as well per @G-Pereira's request
I propose that we breakout the CAN-interface pins from the MCU for future expandability.

- [ ] Suggested pins for CAN on the feeder/STM32F103C8T6:
[PB8 and PB9]

- [ ] Suggested pins for CAN on the Mobo/STM32F407VET6:
[PB8 and PB9] or alternatively [PA11 and PA12]

- [ ] If possible a CAN-breakout header on the feeder with PB8/PB9/3V3/GND would be great.

- [ ] If you want to take it even further, then a footprint for a TCAN337G CAN-transceiver with just a 100nF cap and 120R CAN termination resistor would be the absolute ideal solution.

**Comment by G-Pereira** [comment]
Thank you for your suggestion!
We aren't looking to use CAN in our design for now however, we want to make it possible for people to do so in their builds if they want to!
For such expansions and custom add-ons, we have designed an AUX port on the motherboard such that it can expose multiple interfaces (SPI, I2C, PWM, analog and power). Within these pins, we will make sure to expose the CAN pins as two pins that are also PWM capable to fit both needs.
As for the feeders, ours are designed to work over RS-485 and we don't want to endorse the usage of CAN so we won't expose a header or include a footprint for a transceiver.
