### ISSUE TITLE
Mechanical Left Side - process improvement

### ISSUE THREAD

**Issue by NT7S** [index-machines/index#275]
_Also applies to Right Side_

In my experience in assembling the frame, I think that step 2 (inserting all of the slot nuts at the same time) is too unwieldy to be practical. I tried doing it that way and had various slot nuts falling out as I was trying to secure others.

I believe it would better to place the 2020 extrusion into the FDM frame pieces, and then put slot nuts in as needed for each following steps 4-6, securing the nuts with the screws before moving onto the next. The final two nuts needed for slot E could be added as a final step.

**Comment by daveismith** [comment]
Hi Jason,
I think it depends on your slot nuts. There are a type that you can just
insert from the slot top and tighten to fasten. There are other styles that
must be inserted from the end. Do you know which style you were using? We
might need to add some notes.

**Comment by NT7S** [comment]
Ah, I'm still a bit of a novice when it comes to building things using aluminum extrusion, so I didn't know there were captive slot nuts. I have the ones that can slip in from the top of the slot, which is why they were falling out when I was trying to do it the way depicted in the docs. I agree that it might be good to either spec the captive nuts if you can or make notes about alternate build instructions if you have the slot nuts like mine.

**Comment by paulsykes** [comment]
Ahh this makes more sense now. The nuts I bought were also not captive. Does captive or non-captive have any advantage. It might be worthwhile standardising on one type for the MVP documentation, just to keep things simple? I bought the nuts linked in the bom.csv

**Comment by daveismith** [comment]
@NT7S  / @paulsykes  - could you take a look to see if the updates I've made make more sense. There's a note on the mechanical assembly page as well some notes in the left and right assembly pages.

**Comment by NT7S** [comment]
Thanks, looks good!

**Comment by paulsykes** [comment]
Looks good to me, many thanks.
