### ISSUE TITLE
Feeder bus wires might have been swapped in a recent commit by mistake

### ISSUE THREAD

**Issue by G-Pereira** [index-machines/index#276]
This can either be at the mobo, feeder or feeder floor

**Comment by daveismith** [comment]
Here's the current setup

Mobo Rev 03 U14 | Mobo Rev 03 J17 | Feeder Floor Rev 05 J1 | Feeder Floor Rev 05 J2 | Feeder Mobo Rev05 J3 | Feeder Mobo Rev 05 U7
------------------|-------------------|------------------------|------------------------|-------------------------|--------
A (RS-485+) | **5** (RS-485+) | **6** (RS-485+) | 4/7 (RS-485+) | 2 (RS-485 +) | A (RS-485 +)
B (RS-485-) | **6** (RS-485-) | **5** (RS-485+) | 3/8 (RS-485-) | 3 (RS-485 -) | B (RS-485 -)

Mapping from Feeder Floor to Feeder
Signal | Floor | Feeder
-------|------|-------
GND | 1/10 | 5
1WIRE | 2/9 | 4
RS-485- | 3/8 | 3
RS-485+ | 4/7 | 2
VIN | 5/6 | 1

So, looking at all of this, it seems like there's an issue in the connection between the Mobo J17 and feeder floor J1. ie, pins 5&6 as swapped. 

@G-Pereira, I would suggest you swap pins 5 & 6 on the feeder floor J1

**Comment by G-Pereira** [comment]
You have two pluses at the feeder floor column, can you fix that?

**Comment by daveismith** [comment]
Done. See above comment.

**Comment by G-Pereira** [comment]
Swapped signals on feeder floor fixed!
