### ISSUE TITLE
[FEEDER MOBO] - Logo seems to be rotated

### ISSUE THREAD

**Issue by mebnicher** [index-machines/index#284]
**Motherboard Revision:** REV005

**Enhancement Description:**

The Logo (on top and bottom) seems to need a 180 Deg. Rotation.

<img width="1120" alt="feeder_mobo" src="https://user-images.githubusercontent.com/43633512/115190710-bf767380-a0e8-11eb-91fb-397983474179.png">

**Comment by G-Pereira** [comment]
Fixed! Thanks!
