### ISSUE TITLE
[FEEDER] - Modify J3 so GND is FILO

### ISSUE THREAD

**Issue by ocouch** [index-machines/index#285]
Feeder Rev-05

See discussion in discord starting from:
https://discord.com/channels/688723670461448225/708642821456003123/834812624578543707

Make the GND contact pad longer than the other pins to ensure ground is connected First In Last Out (before power and comms).
Remove the thermal relief from the GND pad on J3.
May also be worth Decreasing the length of VDC - see https://discord.com/channels/688723670461448225/708642821456003123/834855846315425802

WIll need to check the contact position of the spring fingers to make sure not too much pad is removed.

Did a quick and dirty to test, but not making a pull request as I don't think I performed the modification in a maintainable way. For reference the pads are currently 10mmx2mm. I took 1mm from VDC and 2mm from the comms pins.
![image](https://user-images.githubusercontent.com/43231870/115767982-0e741f80-a3ed-11eb-947b-005ece541488.png)

![image](https://user-images.githubusercontent.com/43231870/115767930-fc927c80-a3ec-11eb-8549-349f1017e2e6.png)

**Comment by ocouch** [comment]
Also need to mark this part not to be the included in the BoM.

**Comment by jellewie** [comment]
So here is where I need to report them in the future, great! thanks :))

**Comment by sphawes** [comment]
Thank you for the note! We are likely editing the way that feeders electrically connect to the feeder floor where this FILO method is not needed, closing.
