### ISSUE TITLE
Diameter/teeth for GT2 Drive Pulley (5mm Bore)

### ISSUE THREAD

**Issue by stuartpittaway** [index-machines/index#287]
On this page https://docs.indexmachines.io/docs/mechanical-assembly/x-motor-mount/
it mentions a GT2 drive pulley 5mm bore, but no mention of the number of teeth or diameter of the outer pulley.

Looking at https://ooznest.co.uk/product/2gt-pulleys/
they have options for 16/20/30 tooth GT2 pulleys with 5mm bore and 6.25mm belt width

Page
https://docs.indexmachines.io/docs/mechanical-assembly/x-idler-mount/
also mentions similar GT2 drive pulley - is this the same dimension as the other?

Similar issue with "V-Slot Rollers" on https://docs.indexmachines.io/docs/mechanical-assembly/y-gantry/ 

what dimension are those?

**Comment by daveismith** [comment]
I've updated the specs on the things you mention.
