### ISSUE TITLE
[MOBO] - JLC part for L1 incompatible with footprint

### ISSUE THREAD

**Issue by daveismith** [index-machines/index#290]
**Motherboard Revision:** REV03 beta

**Issue Description:** The LCSC/JLC part which was specified is [C15857](https://lcsc.com/product-detail/Power-Inductors_Sunlord-SWPA8040S220MT_C15857.html/?href=jlc-SMT) 

**Suggested Fix:** Consider [C206321](https://lcsc.com/product-detail/Power-Inductors_Sunltech-Tech-SLW6045S220MST_C206321.html/?href=jlc-SMT).

Note: The alternate part is not rated for the same current level as the original (2.1A) vs suggested (1.8A)

**Comment by G-Pereira** [comment]
Solved!
