### ISSUE TITLE
[DOCS] Electrical Assembly add image

### ISSUE THREAD

**Issue by darigovresearch** [index-machines/index#302]
Page says `TODO: Insert Some Pictures of Index`, thought it would be helpful to raise an issue to help keep track of it. Would supply an image but haven't yet built an index.

Page in question - https://docs.indexmachines.io/docs/electrical/

**Comment by G-Pereira** [comment]
The documentation is now fundamentally different and this issue seems to be addressed, please re-open this issue or file a new one if you think there is still something wrong, thank you!
