### ISSUE TITLE
[MOBO] What's the branch should I used for make the mobo board, and build the marlin firmware

### ISSUE THREAD

**Issue by wchy1128** [index-machines/index#303]
Hello, I have a question about the mobo file and marlin firmware

I find the marlin firmware code can be build use stm32f407, But the master branch mobo board is use chip atmega2560。

So I confuse about which is the pair code and pcb file?

Thanks

**Comment by G-Pereira** [comment]
Helo! We are currently working on releasing Index Mobo rev03 that's why you don't see the correct board there. [Join us](https://discordapp.com/invite/TCwy6De) on Discord to be up to date with us!

**Comment by wchy1128** [comment]
Thanks,I am an engineering about embedded firmware and AI algorithm, If you need, I can join and contribute the project

**Comment by G-Pereira** [comment]
You are more than welcome!
