### ISSUE TITLE
[CAD] - Missing FDM_0004 

### ISSUE THREAD

**Issue by maghostmil** [index-machines/index#304]
I can't found this file on master branch in pnp/cad/3D-Prints

**Comment by ocouch** [comment]
The master branch is old stuff at present. Up to date stuff is in the cad branch

**Comment by G-Pereira** [comment]
@maghostmil FDM-0004 is the other leg. The part is the same as FDM-003.
Plese use the **master** branch for 3d printed parts

**Comment by maghostmil** [comment]
Ah, okay, thanks :) 

PS. 
Which branch can I use for Index BOM (up to date)? Because I can't found it on master branch.

**Comment by G-Pereira** [comment]
We are currently working on a BOM, in the meantime please check the part list at each section [here](https://docs.indexmachines.io/docs/)
