### ISSUE TITLE
[CAD] - Suggestion - split front legs in half

### ISSUE THREAD

**Issue by stuartpittaway** [index-machines/index#314]
Given that the front legs take several hours to print, I suggest that consideration is given to split the leg in half (horizontally) similar to the images.

I see this having benefits such as:

1. As the top half of the part is likely to change over time, several hours can be saved by not reprinting the bottom "feet"
2. Parts can be printed on smaller printers
3. Parts can be printed simultaneously if multiple printers are available
4. The structure retains its strength via the 20x20 rod, with additional bolts being used for the foot and the top section
5. Less waste (environment) and filament is used if only the top section changes

![image](https://user-images.githubusercontent.com/1201909/118392218-5d018c00-b630-11eb-8e11-981f19ab3328.png)

In this image, an M5 bolt could actually run vertically down the part to secure onto the top of the 20x20 rail.  Alternatively if the part can be widened, it could bolt onto both left and right sides of the rail (this may reduce width for part feeders).

![image](https://user-images.githubusercontent.com/1201909/118392234-74407980-b630-11eb-9209-65b06ab291b8.png)

**Comment by maghostmil** [comment]
It looks good. Will you include Freecad or STL files for that? I can test this solution.

**Comment by stuartpittaway** [comment]
I'm happy to provide the cad files, if approved

**Comment by sphawes** [comment]
I'd be worried about losing rigidity that we retain by keeping everything in one print. Also, this is quite an old ticket and lots has changed since and quite a bit has been tested to be working using just one part for the leg, rather not throw a curveball into the mix now. I'm going to close out!
