### ISSUE TITLE
[CAD] Index Fastener Errors

### ISSUE THREAD

**Issue by arturo182** [index-machines/index#327]
I think I found two small issues in the assembly:

1. The screws used for the NEMA11 are M3:
![image](https://user-images.githubusercontent.com/249082/122624586-1d9be480-d0a1-11eb-87dd-d868ae2b6bef.png)

but should be M2.5:

![image](https://user-images.githubusercontent.com/249082/122624617-4623de80-d0a1-11eb-8950-64d7e195a1e3.png)

2. There are two M3 screws on top of each other for the camera up mount:
![image](https://user-images.githubusercontent.com/249082/122624644-83886c00-d0a1-11eb-88c8-59c689604b88.png)

and

![image](https://user-images.githubusercontent.com/249082/122624650-8f742e00-d0a1-11eb-9aec-4764e49acc31.png)

This also affects the BOM which specifies 5pcs of M3x30, but in reality only 4 are needed.

**Comment by lucian151** [comment]
We should switch the NEMA 11 mounting screws to ISO4762 Screw M2.5x8 per this feedback. Good catch!

**Comment by sphawes** [comment]
This has been fixed, closing!
