### ISSUE TITLE
[CAD] - FDM11 X gantry M3 nut holes too small

### ISSUE THREAD

**Issue by stuartpittaway** [index-machines/index#331]
On FDM0011 X Gantry, the M3 nut holes are too small.

The M3 nuts are drawn inside a 5.75mm circle, the distance between flats is 4.97mm

According to this https://www.engineersedge.com/hardware/standard_metric_hex_nuts_13728.htm

The flats should be between 5.32 and 5.50mm.  

![image](https://user-images.githubusercontent.com/1201909/123218671-ea53be00-d4c3-11eb-9920-549844c0e8bb.png)

I've 3d printed this part and can confirm the holes are very tight - I've managed to damage a couple of them and now have an M3 bolt stuck with a spinning nut inside the 3d part!

Increasing the hole diamter to 6.25mm appears to fix the issue, although I would recommend using the pocket hole feature of FreeCad to place an M3 part.

**Comment by sphawes** [comment]
This fix was merged, closing.
