### ISSUE TITLE
[CAD] - bolt/machine screw lengths

### ISSUE THREAD

**Issue by stuartpittaway** [index-machines/index#333]
Most of the screw lengths are a perfect fit when viewed on the Freecad model, however in real life, the bolt only just reaches the end of the nut.

If you use nylon/nyloc nuts, then there isn't enough thread to reach the end of the nut.

I suggest an extra 5mm is added to most of the 40mm M5 screws

**Comment by G-Pereira** [comment]
Screws are supposed to just reach the end of the nut, I am in the process of printing the new parts and will validate this

**Comment by stuartpittaway** [comment]
This is particularly relevant if the use of NYLOC style nuts is used - these are typically longer than standard nuts, and the thread won't reach the end of those.

**Comment by lucian151** [comment]
I'm trying to do a BOM freeze for the Index Fastener kits, we might want to revisit this ticket before then.
