### ISSUE TITLE
[MOBO] - Move Feeder RS485 transceiver serial interface to hadware serial pins

### ISSUE THREAD

**Issue by G-Pereira** [index-machines/index#339]
**Motherboard Revision:** REV04

**Enhancement Description:**
- Use Hardware serial to improve communication speed and improve automatic firmware flashing time

**Comment by G-Pereira** [comment]
Fixed on rev03!

**Comment by stuartpittaway** [comment]
Is the modification possible to existing v3 boards using bodge wires?

**Comment by G-Pereira** [comment]
Yes, look at the pins that are in use now and make a bodge. We will provide configuration files for both versions. You won't notice the difference until we move to firmware flashing over RS485, which will take a long time until we look at it
