### ISSUE TITLE
[MOBO] - Reduced corner radius on next mobo revision. 

### ISSUE THREAD

**Issue by LoneWalkerWolf** [index-machines/index#341]
**Motherboard Revision:** REV04

**Enhancement Description:** I know this is really minor and probably is only bothering me, but the corners of the motherboard just look slightly out of proportion in regards to the rest of the board. It would be awesome if you guys could reduce the radius of the corners from 5mm down to something like 2.5mm or even 2mm. I think this would give the mobo a more professional look (and not bug me as much :3) All of my PCBs have this corner radius, and I do think it looks amazing. This shouldn't impact features of the mobo much, in fact, it would actually increase board area allowing for more routing options if necessary. 

I attach a photo of one of my PCBs with the corners at a 2.5mm radius. 

![IMG_20210705_104056](https://user-images.githubusercontent.com/63847434/124452108-fd954200-dd7d-11eb-9282-d39da86766d0.jpg)

**Comment by sphawes** [comment]
hey @LoneWalkerWolf! I'm going to close this, we currently have the radius set such that the center point is concentric with the mounting holes. We've also got some infrastructure in place that relies on the board outline being what it is (namely the pcb tester jig), plus I'm fond of how it looks :) Thanks for the suggestion!
