### ISSUE TITLE
[MOBO] - Rev 3 - "QUICC" instead of "Qwiic"

### ISSUE THREAD

**Issue by arturo182** [index-machines/index#342]
The label for the Qwiic connector is wrongly spelled as "Quicc"

![image](https://user-images.githubusercontent.com/249082/124475662-40691100-dda2-11eb-8a9f-43d61a9a2b49.png)

Also, if we want to call the board "Qwiic or Qwiic-Compatible", we have to use their logos, more details here:
https://www.sparkfun.com/qwiic#faqs

**Comment by G-Pereira** [comment]
Fixed, thanks!
