### ISSUE TITLE
[MOBO] - Reverse polarity protection mosfet is reversed

### ISSUE THREAD

**Issue by G-Pereira** [index-machines/index#349]
**Motherboard Revision:** REV03

**Issue Description:**
- FDS4435BZ reverse polarity mosfet have its drain and source reversed.

**Suggested Fix:**
- Rotate mosfet without moving footprint to keep the same stencil

**Workaround:**
- remove the IC from the board
- bypass it by shorting drain and source
- keep in mind that this removes reverse polarity protection

**Comment by Jnesselr** [comment]
I don't understand how simply rotating it would work. It looks like it is pin 4 for the gate, 1 for the drain, and 8 for the source on the schematic. On the chip itself, pin 1-3 are source, 4 is gate, and 5-8 are drain.

Rotating it 180 degrees seems like it would connect the source and gate together.

**Comment by G-Pereira** [comment]
@Jnesselr I think you got it by our yesterday's conversation but I'll post here so other people can understand too.
I don't mean we can rotate the IC because like you've seen there's no orientation that would fix it, a new board spin up is needed.

**Comment by G-Pereira** [comment]
I was looking at it wrong. This is correctly connected as it is on the current beta version!
