### ISSUE TITLE
[Docs] Error in Mechanical Assembly - Right Side

### ISSUE THREAD

**Issue by nkappler** [index-machines/index#361]
![grafik](https://user-images.githubusercontent.com/9429273/129163156-b00c5c07-8505-4d0d-aeaa-c3b152516d5c.png)

Should be FDM-0004-01

**Comment by mmb-davidsmith** [comment]
Fix is mainly complete. Just need to trigger the page it links to to rebuild.

**Comment by daveismith** [comment]
Fix is mainly complete. Just need to trigger the page it links to to rebuild.
