### ISSUE TITLE
[MOBO] - replace TL072IDR by TL082IDR?

### ISSUE THREAD

**Issue by alvaro-mgv** [index-machines/index#372]
TL082IDR has basically the same specs, footprint and pin connections than TL072IDR, with more than 2,200 units available in LCSC. Actually, TL072IDR is not found in LCSC, Mouser or Digikey at this time. Is it possible to replace TL072IDR by TL082IDR?

**Comment by G-Pereira** [comment]
Thank you for your suggestion! TL072 is a pretty popular IC resulting in high availability, which was why it was selected. Sadly that's not true anymore in the chip shortage foundries are facing. From the datasheet it seems compatible but it doesn't make much sense to swap on the design given the current market's volatility although I see no issues if you want to use it in your board. I am closing this. Thanks again!
