### ISSUE TITLE
[MOBO] MOBO BOM File "mobo_bom_jlc.csv" column mislabeled

### ISSUE THREAD

**Issue by Phase4logic** [index-machines/index#375]
L1 in the schematic has the LCSC Part Number field populated with C168077.  However, the LCSC part number field in the BOM file [here](https://github.com/index-machines/index/blob/master/pnp/pcb/mobo/export/mobo_bom_jlc.csv) is blank. 

I think that the column in the BOM file is mislabeled.  It is labeled "LCSC Part #" and I think it should be labeled "JLC PCB Part #".  I see sometimes they are the same part # and sometimes they are different.  In this case, the inductor has no JLC PCB Part # filled in, which would explain why it is blank in the BOM.

**Comment by daveismith** [comment]
JLC required that column to be LCSC when the export scripts were developed. It seems like they now suggest JLCPCB Part #. 

See https://support.jlcpcb.com/article/80-bill-of-materialsbom-file-for-smt-assembly

**Comment by martinbogo** [comment]
They aren't one and the same?

**Comment by daveismith** [comment]
We have separate attributes in the schematic as not all LCSC parts are available at JLCPCB. As such sometimes there's a cheaper option on LCSC that we can't use with JLC.

**Comment by G-Pereira** [comment]
This issue has been solved since those files were removed and the existing BOM was updated (now via an automated script)
