### ISSUE TITLE
[CAD] [RingLight] Thickness of RingLight PCB

### ISSUE THREAD

**Issue by ttahsin-bey** [index-machines/index#379]
According to the PCB-File of the RingLight the thickness of the PCB should be 1.6 mm (see Pcbnew:File/Board Setup).

This height does not match the space for the pcb in FDM-0015 (down-light-mount) and FDM-0019 (up-light-mount). Here the height of the cutout for the PCB is 1.25 mm...

**Comment by G-Pereira** [comment]
This has been discussed and the board thickness needs be 1.6mm and the FDM part is designed to clamp it hence the clearance. Thanks!
