### ISSUE TITLE
Motherboard BOMs call for A4988

### ISSUE THREAD

**Issue by feldon30** [index-machines/index#396]
These BOM files pass through a description field of "Pololu Breakout Board, Stepper Driver A4988" and part name of "Pololu_Breakout_A4988". This suggests that A4988 stepper motor driver modules are the recommended part. In fact, TMC2209s are preferred. I suggest renaming the part name and description field to clear up any confusion.

index/pnp/pcb/mobo/export/mobo-bom.csv
index/blob/master/pnp/pcb/mobo/export/mobo-bom.html

**Comment by G-Pereira** [comment]
This issue has been solved since those files were removed and the existing BOM was updated (now via an automated script)
