### ISSUE TITLE
Update CI to Export Artifacts

### ISSUE THREAD

**Issue by sphawes** [index-machines/index#401]
Please fill out the following:
- Build Number where this issue is present. (This is the same as the most recent tag number): v1.2.2
- Is this recording an active issue, or suggesting an improvement?: Active Issue
- Are you just logging an issue, or do you have a solution in mind?: Solution in mind
- Please describe the issue:
We have removed CI script that automatically exports schematics, STLS, and other static files and re-commits them back to the repo. We've done this because it has greatly increased the size of the repository, and we're coming up to some limits that Github has imposed. As of now, there is no solution for auto-exporting files for ease of viewing and use.

- Please describe your suggestion solution, if you have something in mind:
As discussed, we'll instead save the exported files as Artifacts. These are not part of the repo themselves, but are still easily downloadable and viewable.

**Comment by stuartpittaway** [comment]
Artifacts are now being generated for the STL files using Github Action CI

**Comment by G-Pereira** [comment]
Yes, this has been addressed!
