### ISSUE TITLE
Export STL files in proper print orientation

### ISSUE THREAD

**Issue by qwertymodo** [index-machines/index#419]
I'm not sure how easy it would be, or if it can even be properly automated, but if possible it would be nice if the STL files were exported in proper print orientation, so they come up in the correct orientation when loading them in slicer software.  Most (if not all) slicers expect Z-up.

**Comment by stuartpittaway** [comment]
This is most definitely on the to do list. A lot of the parts have a print plane already defined in the cad model.

@Jnesselr is hopefully picking this one up

**Comment by Jnesselr** [comment]
I believe this to be done now on cad-staging. Please open a new issue if you find any parts that are now oriented incorrectly.
