### ISSUE TITLE
Release v2.0.0 is missing STL for FDM-0045_corner_bracket

### ISSUE THREAD

**Issue by jonnerd154** [index-machines/index#440]
Please fill out the following:
- **Build Number where this issue is present:**
   v2.0.0 (8bb4558761e874d179813e4c29948d99a9b9f893)
- **Is this recording an active issue, or suggesting an improvement?:**
   Active Issue
- **Are you just logging an issue, or do you have a solution in mind?:**
   Solution in mind, see below.
- **Please describe the issue, including relevant part numbers and screenshots of the issue in CAD if possible:** 
   The `index_bom.md` file indicates that qty 2 of `FDM-0045_corner_bracket` are required, but that part is not in the source tree, nor in the Release Assets.
- **Please describe your suggestion solution, if you have something in mind:**
   Include the file in Release Assets, or remove the requirement from `index_bom.md`, if that part is not required.

**Comment by stuartpittaway** [comment]
Thanks for the issue, that part is optional and has been renamed to FDM-9001_squaring-bracket.FCStd

The BOM needs to be corrected.

**Comment by sphawes** [comment]
BOM has been corrected! You can redownload from the release for the updated version. Thanks for the notice @jonnerd154. Closing this!
