### ISSUE TITLE
List which 3D printed files should be printed in "Gantry Settings"

### ISSUE THREAD

**Issue by MakeItHackin** [index-machines/index#447]
It would be helpful to the user to list which 3D printed files should be printed in "Gantry Settings" in the documentation.  Not sure if there's an automatic way to do it or not, but a few people have asked in the discord.

**Comment by oursland** [comment]
Work towards this is in review on PR #441

**Comment by sphawes** [comment]
This has been fixed in the v2.1.0 release!
