### ISSUE TITLE
[CAD] - Increase 3D printed holes for spoolHolder

### ISSUE THREAD

**Issue by Decee1** [index-machines/index#45]
The holes on the spoolHolder is too tight. Should be increased to around 3.2-3.3mm. Currently they are 3mm which requires your 3D printer to be extremely precise in it's printing.

**Comment by sphawes** [comment]
Going to close this, CAD has changed significantly since then! We're putting a more concerted effort into print tolerances now, so this shouldn't be an issue moving forward! :D
