### ISSUE TITLE
OpenPNP Bottom Camera Position Proceedure final step

### ISSUE THREAD

**Issue by InfiniteNesLives** [index-machines/index#457]
From procedure here: https://docs.opulo.io/openpnp/calibration/bottom-camera-position/

Last step (3) reads: "Jog the nozzle to be perfectly centered over the bottom camera, and click on the blue nozzle icon to capture the position. Your bottom camera position is now saved!"

"capture the position" is too ambiguous on what button to click on in openPNP.  I "captured the position the camera is centered on" because I thought that made sense as I'm working with a camera calibration.  But that's wrong, it should be "capture the position that the tool is centered on".

It's a minor thing, but quite a vital detail.  Clicking the wrong button here will jam the nozzle into the datum board on a subsequent homing procedure due to the offset you end up with.  Probably helpful to have a graphic to help ensure others don't make this mistake. :)

![image](https://user-images.githubusercontent.com/28371160/155735060-182f7de2-a82f-4fd2-b70e-7c7fca76b3bd.png)

**Comment by sphawes** [comment]
@InfiniteNesLives Thanks for the note! I'll add that exact screenshot to the docs with clearer language to help remove the ambiguity!
