### ISSUE TITLE
Ring Light PCBA: Mech interference between [FDM-0015-02, FDM-0019] and C45

### ISSUE THREAD

**Issue by jonnerd154** [index-machines/index#459]
Please fill out the following:
- Build Number where this issue is present. (This is the same as the most recent tag number): v2.0.1
- Is this recording an active issue, or suggesting an improvement?: Active issue
- Are you just logging an issue, or do you have a solution in mind?: Solution in mind
- Please describe the issue, including relevant part numbers and screenshots of the issue in CAD if possible: When installed inside FDM-0015-02, the capacitor at the edge of the board (C45) interferes with the inner wall of FDM-0015
- Please describe your suggestion solution, if you have something in mind: Cut a small relief in FDM-0015 to provide clearance to the component.

For a quick fix on already-printed parts, some xacto-ing works. :)
![IMG_5338](https://user-images.githubusercontent.com/759994/155823683-a347aa5b-0079-4f6b-bb4b-692ecb51ff34.jpg)

**Comment by TheSeven** [comment]
The same issue applies to FDM-0019 as well.

**Comment by stuartpittaway** [comment]
FDM-0019 is fixed by issue #471

**Comment by stuartpittaway** [comment]
Updated part now has cut out for C45 capacitor and also mouse bite edges.  Removed alignment notch as that now conflicts with mouse bite slots.

Updated to part rev. 3

![FDM_0015_3](https://user-images.githubusercontent.com/1201909/156344337-902cab19-20e4-4af6-9c60-971cb5fdf31b.png)

**Comment by sphawes** [comment]
Fix released in v2.1.0!
