### ISSUE TITLE
Y Gantry Assembly

### ISSUE THREAD

**Issue by AlanaCat** [index-machines/index#462]
![Screen Shot 2022-02-25 at 9 29 48 PM](https://user-images.githubusercontent.com/65329315/155830539-def6bb04-1d76-4be1-a36f-a37568d7cd93.jpg)

**Comment by jesseleonard** [comment]
Probably needs to be  "M3x8mm" if it's the same as the Left Side and Right Side assembly.
I tried the M3x8mm on mine and it seemed to go in just like the left and right side assembly.
