### ISSUE TITLE
FDM-0019 Up Light Mount Changes

### ISSUE THREAD

**Issue by AlanaCat** [index-machines/index#471]
- Build Number where this issue is present. (This is the same as the most recent tag number): FDM-0019-01
- Is this recording an active issue, or suggesting an improvement?: Both
- Are you just logging an issue, or do you have a solution in mind?: I have a solution
- Please describe the issue, including relevant part numbers and screenshots of the issue in CAD if possible: Depth for the ring light PCB is only 1.25mm, should be 1.6mm. There is also a capacitor that has been previously mentioned that interferes with the print, and I made som cutouts for the mouse bites so it just fits without filing.
- Please describe your suggestion solution, if you have something in mind: I have made the changes and included the .step file (in a .zip).
[FDM-0019_up-light-mount_Body_001-AC v2.step.zip](https://github.com/index-machines/index/files/8155120/FDM-0019_up-light-mount_Body_001-AC.v2.step.zip)

**Comment by stuartpittaway** [comment]
@AlanaCat can I ask you to confirm that the ring light PCB was from a Lumen kit, and was 1.6mm thick ?

**Comment by AlanaCat** [comment]
Yes, it is from the kit.
![D2B8611E-7540-47BA-92F3-B44391E9A71E](https://user-images.githubusercontent.com/65329315/156131659-fdead30b-4f44-467f-83a6-e5be259caf7b.jpeg)

**Comment by stuartpittaway** [comment]
Thank you.

**Comment by stuartpittaway** [comment]
@AlanaCat based on the STEP model you provided, I've made similar changes to the FreeCad model.  

This is checked into the cad-staging branch, if you get chance would be good for you to review to see if it compares with your design/PCBs

![image](https://user-images.githubusercontent.com/1201909/156154098-b3cd34ee-6743-4124-b662-f3c9167d3cda.png)

**Comment by sphawes** [comment]
Merged!
