### ISSUE TITLE
Automatic nozzle changing notes

### ISSUE THREAD

**Issue by InfiniteNesLives** [index-machines/index#477]
I got automatic tool changing fully implemented today, had a few stumbling points that would probably be worth adding to the opulo docs for the benefit of other users:  https://docs.opulo.io/openpnp/calibration/auto-toolchanger/

- [x] Nozzles require lubrication for good insertion, I might have missed it in the docs, but instructing the user to utilize O-ring grease from their nozzle kit may be helpful.  Otherwise vegtable oil was a viable substitute which is what I ended up using and it did the trick for me.  Jon Raymond recommended 'air tool oil' as another option that might be more easily sourced locally.

- [x] I ended up having to drive my nozzle holder in ~3mm instead of the 1mm suggested in the opulo doc, might be worth suggesting the user to experiment with different values while their nozzles are breaking in.

- [x] It took me quite awhile to figure out how to actually enable automatic tool changing, I couldn't find the setting in the openpnp docs either.  So probably helpful to point this out to the user in the opulo doc, listed under machine settings, referencehead H1, nozzles "refernencenozzle N1", "automatic toolchanger enabled?"
![image](https://user-images.githubusercontent.com/28371160/156480976-2e8cba1d-5fa2-4be9-906c-0d8d3e98c929.png)

- [x] There's a nifty trick in openpnp to set one nozzle as a template that can be cloned to other nozzles.  It's not the easiest to explain, but useful so might be worth just sending the user a link to the openpnp docs to learn how to use it:
https://github.com/openpnp/openpnp/wiki/Nozzle-Tip-Changer#cloning-settings

**Comment by sphawes** [comment]
Fantastic notes @InfiniteNesLives, thank you! I'll integrate these into docs now.
