### ISSUE TITLE
Opulo openpnp docs should recommend more calibrations before first job

### ISSUE THREAD

**Issue by InfiniteNesLives** [index-machines/index#482]
After completion of the last openpnp calibration step "automatic tool changer", the next step in opulo docs is your first job and a congratulations that your pnp is now calibrated.  While many calibrations are complete and you could start your first job, you're likely to find calibration problems especially related to your nozzle - camera offsets.  It's easy to get excited about your first job and not realize there a more calibrations you should perform to get decent placement accuracy.  I had issues with placement accuracy on my first real jobs and thought I needed to keep revisiting the calibrations already performed.  It wasn't until Bobbe in discord reminded me that the precise nozzle - camera offset calibration would likely correct many of my precision problems and it absolutely did.

I understand the opulo docs are not meant to cover everything in openpnp, nor should they.  But they are meant to transition you from the build to running jobs in openpnp.  My suggestion would be for the addition of one more 'generic further calibrations' step to be added to opulo calibration doc page.  Perhaps reading something like the following:

Congratulations on completing the intial calibration steps on your new lumen PNP!  At this point your machine should be calibrated just well enough to start your first job, but you'll probably find issues with placement accuracy.  If you want to start your first job and see your lumen roughly place some components, go for it in the next section.  But don't forget to keep working on the "issues & solutions" tab in openpnp that will help you further calibrate your lumen, for help with those steps we recommend reviewing the openpnp docs.  Namely you should complete the "Calibrations Milestone" prior to expecting your lumen to run it's first real manufacturing job.

![image](https://user-images.githubusercontent.com/28371160/157050187-0c23198a-f82e-47ba-a47a-90125134416c.png)

**Comment by sphawes** [comment]
Thank you for this @InfiniteNesLives! I'll update that last page on the docs site based on this!
