### ISSUE TITLE
OpenPnP Vac Sensor REGEX

### ISSUE THREAD

**Issue by AlanaCat** [index-machines/index#489]
Please add the RegEx for vac sensing to the instructions for setting up OpenPnP and consider including it in the default machine.xml in the release files. This is the code that works for me:

^.\*V:(?\<Value>\d+).\*

![Screen Shot 2022-03-14 at 9 26 33 PM](https://user-images.githubusercontent.com/65329315/158306727-5f5bf56c-5251-48ce-a782-307d258d0f2b.jpg)

**Comment by stuartpittaway** [comment]
I've also used similar regex.

```
^V:(?<Value>-?\d+).{1,20}$
```

The ACTUATOR_READ_COMMAND that I use (left nozzle/sensor)

```
M3426 G4 C1 I1
```

**Comment by sphawes** [comment]
Thank you for this @AlanaCat! I'll be adding this into the next update of the opnp config.
