### ISSUE TITLE
Add Examples of Importing Data Files into OpenPnP from Common Layout Tools

### ISSUE THREAD

**Issue by solarmax1** [index-machines/index#490]
Please fill out the following:
- Build Number where this issue is present. (This is the same as the most recent tag number): 2.1.0
- Is this recording an active issue, or suggesting an improvement?: Improvement
- Are you just logging an issue, or do you have a solution in mind?: Add this example to documentation
- Please describe the issue:
Add examples for importing placement data from popular layout tools.  For example, several of us use DipTrace.  The data exported requires some manual editing to work with OpenPnP.  

- Please describe your suggestion solution, if you have something in mind:
Two of us have successfully exported PnP data from DipTrace 4.2.0.1.   The column titles in the first line need to be  labeled with the field names as as shown in this example.  The user needs to manually edit the heading for X, Y and the Component Height.  Shown below are first few lines of an example file that works.  Look carefully at the first line and make sure that your titles match.

RefDes,Pattern,X (mm),Y (mm),Side,Rotate,Value,Height(mm)
C1,CAPP_1210_N,84.684,25.044,Top,270,4.7u,1.35
C2,CAP_1210_N,77.572,24.994,Top,90,22u,1.35
C3,CAP_1206_M,22,26,Top,270,0.1u,1.35
C4,CAP_1206_M,22,21,Top,270,0.1u,1.35

**Comment by sphawes** [comment]
Hey @solarmax1! This falls outside the scope of this project and is solely related to OpenPnP. Check out their page about importing position data here: https://github.com/openpnp/openpnp/wiki/Importing-Centroid-Data
