### ISSUE TITLE
Vacuum sensing test missing step to actuate valve

### ISSUE THREAD

**Issue by InfiniteNesLives** [index-machines/index#491]
https://docs.opulo.io/docs/testing/actuator-check/#vacuum-sensors

The vacuum sensing test in opulo docs never instructs you to actuate (power on) the vacuum solenoid valve.  Unless I'm mistaken, this is a vital & required step to draw vacuum on the sensor.  Without powering the valve, the line is vented to atmospheric pressure.  I don't have vacuum sensing enabled on my machine so I could be wrong, but several users are reporting problems with the vacuum sensing test and I think this is probably why.

**Comment by atanisoft** [comment]
I'm working on configuring OpenPnP for my projects and after importing the Opulo machine.xml (via overwrite in config directory) I found there are a couple Actuators that are defined on the GCodeDriver that don't exist:
https://github.com/index-machines/index/blob/01702144b94ddbe14eabd6cf24d7e3c43b42dba0/openpnp/machine.xml#L253-L263

I haven't dug into the Marlin code to see exactly what these codes do in regard to the Opulo but I suspect this may be related to the vacuum sensing.

**Comment by jellewie** [comment]
Just looked up the Gcode of @atanisoft , just here to report them:

https://marlinfw.org/docs/gcode/M042.html Set Pin State - M42 Ignore Pin State Mode
https://marlinfw.org/docs/gcode/G004.html Dwell - G4

https://marlinfw.org/docs/gcode/M106.html Set Fan Speed - M106 MaterialIndex index speed secondary

https://marlinfw.org/docs/gcode/M150.html Set RGB(W) Color  - M150 intensity pixel intensit intensity strip intensit intensity

**Comment by atanisoft** [comment]
Yeah, I don't know if these actuators are important or not but they are defined on the GCodeDriver but the `head-mountable-id` value is invalid for any of the defined actuators.

**Comment by stuartpittaway** [comment]
> The vacuum sensing test in opulo docs never instructs you to actuate (power on) the vacuum solenoid valve.

It may be missing from the documentation, but Stephen was using these two commands when the pump gets switched on.  This means both the pump and the valve operate together, which is how he's been running.

There were a few comments about OpenPNP not opening/closing the valve at the correct point in the pnp process if the valve was a separate actuator.  I've tried both and didn't see a problem.

"Pump Left" actuator GCODE ```ACTUATE_BOOLEAN_COMMAND```
```
{True:M106 P1}{False:M107 P1}
{True:M106 P0}{False:M107 P0}
```

**Comment by stuartpittaway** [comment]
> https://marlinfw.org/docs/gcode/M042.html Set Pin State - M42 Ignore Pin State Mode

Probably don't need those pin states as the outputs on the mobo are connected to the fan header/pins, so M106 can be used.

**Comment by InfiniteNesLives** [comment]
Bumping this issue as people are still actively running into this problem..

**Comment by sphawes** [comment]
@InfiniteNesLives Thanks for reporting this, definitely incorrect on the docs side; should have the extra line to actuate the valve as well. This will be fixed with the next documentation release we're prepping for now!
