### ISSUE TITLE
Light Ring brightness/color control

### ISSUE THREAD

**Issue by alphaomega16** [index-machines/index#493]
Please fill out the following:
- Build Number where this issue is present. (This is the same as the most recent tag number):
V2.0.x
- Is this recording an active issue, or suggesting an improvement?:
Both
- Are you just logging an issue, or do you have a solution in mind?:
Looking for documentation to enable feature
- Please describe the issue:
Unable to locate documentation for configuring the actuators needed to change light ring brightness or change colors. 
Openpnp documentation refers to configuring a profile for the LED actuator. https://github.com/openpnp/openpnp/wiki/Setup-and-Calibration:-Actuators
- Please describe your suggestion solution, if you have something in mind:
Addition of documentation relating to light ring functions

**Comment by stuartpittaway** [comment]
Heres the basic steps to implement this.  If we use the UPLIGHT as an example.

1. In OpenPNP, locate the "Actuators" in "Machine Setup".  This on the machine level actuators, not the nozzle/head one.
2. Create a new "ReferenceActuator" - we will call it "Up_light_Profile"
3. Change the "Value type" to PROFILE, and other settings like the screenshot ![image](https://user-images.githubusercontent.com/1201909/159870452-c5c26913-9409-4cfe-baf0-2811c11e0cda.png)
4. In the "Profiles" tab, create the default ON/OFF values, along with any colors required.  This is standard RGB color maps.
![image](https://user-images.githubusercontent.com/1201909/159870744-25e19423-8dae-4832-9fd0-228b24f12412.png)
5. Set the "Actuator 1" to be the relevant "up light" actuator (or create this if you don't already have it)
6. Apply/Save those settings
7. Edit the "Up_light_Actuator", and set the values like the image. 
![image](https://user-images.githubusercontent.com/1201909/159871159-4401f675-5d86-4c43-ba77-8d346f2fc0f8.png)
8. Edit the up camera settings to use the new profile.
![image](https://user-images.githubusercontent.com/1201909/159871401-8c7e38c5-7c2d-46c2-8fec-26526cafe5de.png)
9. Finally, edit the GCODE driver settings for the actuator to pass the RGB command into Marlin.
![image](https://user-images.githubusercontent.com/1201909/159871646-7cff5ef8-3703-44b1-8e27-85aefabed99d.png)
