### ISSUE TITLE
MOBO Gerber Files

### ISSUE THREAD

**Issue by TGiles1998** [index-machines/index#507]
Hi,

I cant seem to find the Gerber files anywhere. Could I be pointed in the right direction?

Many thanks,

Thomas

**Comment by daveismith** [comment]
Check out the pnp_mobo_files.zip (and similar files for feeders, ring lights and datum board) in the [releases](https://github.com/index-machines/index/releases)

**Comment by TGiles1998** [comment]
Thank you very much!
