### ISSUE TITLE
Update the Firmware section of docs missing step

### ISSUE THREAD

**Issue by solarmax1** [index-machines/index#513]
Please fill out the following: 2.1.0
- Build Number where this issue is present. (This is the same as the most recent tag number):
- Is this recording an active issue, or suggesting an improvement?: Suggesion
- Are you just logging an issue, or do you have a solution in mind?:  Logging an issue
- Please describe the issue: In the assembly docs under "Update the Firmware"  step 2, the user also needs to install the "Auto Build Marlin" extension to VSCode.  

- Please describe your suggestion solution, if you have something in mind:

**Comment by Memnarch1113** [comment]
@sphawes I was under the impression that Platformio could do this without the Auto Build Marlin extension? Or do you really need both? (I have both from my flashing attempts but I don't remember if I actually used the Auto Build Marlin one)

**Comment by atanisoft** [comment]
@Memnarch1113 I've successfully built Marlin with only PIO Core (CLI only, no integration to VSCode etc). There is no specific need for `Auto Build Marlin` plugin if you follow the steps listed in the docs today (modify platformio.ini to specify default env or from command line specify the specific env to be built).
