### ISSUE TITLE
Docs pages should include list of parts required at top

### ISSUE THREAD

**Issue by atanisoft** [index-machines/index#523]
Please fill out the following:
- Build Number where this issue is present. (This is the same as the most recent tag number): 2.1.1
- Is this recording an active issue, or suggesting an improvement?: improvement
- Are you just logging an issue, or do you have a solution in mind?: solution
- Please describe the issue: Documentation does not include required parts (printed or otherwise) for each step except inline with the documentation, sometimes without references.
- Please describe your suggestion solution, if you have something in mind:
Documentation can be improved by adding a table at the top of the page indicating the required parts for the steps on the page, this should include part counts. Additionally all parts should include a part ID reference (FTS-XXXX, FDM-XXXX, etc) that can be cross referenced from the BOM.

**Comment by sphawes** [comment]
@atanisoft thanks for the notice! and thanks @jazzychad for the contribution! closing.
