### ISSUE TITLE
Improved Feeder Mounting Rigidity

### ISSUE THREAD

**Issue by sphawes** [index-machines/index#53]
The feeder is currently only secured to the front rail using gravity, and a bit of friction from the pcb. A small latching mechanism needs to be added to the feeder that:
- holds the feeder onto the rail
- is repeatable with where it holds the feeder
- release mechanism can be released with feeders on either side

**Comment by G-Pereira** [comment]
@sphawes any ideas for this? Maybe someone else can work on this.

**Comment by sphawes** [comment]
closing this as we're revamping the feeder holistically and this is being taken into consideration
