### ISSUE TITLE
FDM-0008 missing 'Print using gantry settings' in pnp/cad/index_bom.md vs. main Opulo docs

### ISSUE THREAD

**Issue by mtnrbq** [index-machines/index#530]
Please fill out the following:
- Build Number where this issue is present.  2.1.1
- Is this recording an active issue, or suggesting an improvement?: Documentation discrepancy
- Are you just logging an issue, or do you have a solution in mind?: Solution
- Please describe the issue: Discrepancy in specification of print settings for FDM-0008 part between main docs and BOM.
- Please describe your suggestion solution, if you have something in mind: update pnp/cad/index_bom.md to match main docs - i.e. 'Print using gantry settings' for FDM-0008

**Comment by sphawes** [comment]
thanks for the issue @mtnrbq! I've fixed this in the docs.
