### ISSUE TITLE
MM/pixel calibration is not clear what should / should not be inside the bounding boxes

### ISSUE THREAD

**Issue by atanisoft** [index-machines/index#542]
Please fill out the following:
- Build Number where this issue is present. (This is the same as the most recent tag number): 2.1.2
- Is this recording an active issue, or suggesting an improvement?: active
- Are you just logging an issue, or do you have a solution in mind?: solution in mind
- Please describe the issue:  MM/pixel calibration lacks clarity of what exactly is expected/required to be inside the bounding box.
- Please describe your suggestion solution, if you have something in mind: Add a picture showing the expected bounding box to use as reference when calibrating both top and bottom cameras.

**Comment by sphawes** [comment]
@atanisoft thanks for the poke on this one, forgot to include it in my commit message! closing.
