### ISSUE TITLE
Update BOM for the Index Frame

### ISSUE THREAD

**Issue by sphawes** [index-machines/index#62]
The frame BOM is out of date, and needs to be updated with good sources for purchase.

**Comment by G-Pereira** [comment]
Hi, I have noticed the teflon tube is missing and the limit switch is the standalone one and not the module.

**Comment by daveismith** [comment]
I think we need to go through the assembly and add in all of the fasteners using the fasteners workbench. It supports a BOM function which hopefully we could automate with a script similar to what already exists for the STL file generation.

From there we might want to add a lookup for some common suppliers for each part, but that shouldn't be too complex to do with a small python script.

**Comment by G-Pereira** [comment]
Done!
