### ISSUE TITLE
Ringlight PCB needs updated connector footprints

### ISSUE THREAD

**Issue by sphawes** [index-machines/index#87]
The ringlight PCB needs an upright 3-pin JST XH connector on back, and a right angle 3-pin JST-XH connector on the front. This will make cable routing easier for both the up and down orientations. (SMD for both.)

Also, the connector pinout should match the standard servo pinout (SIG-5V-GND), and match the mobo.

**Comment by G-Pereira** [comment]
The right angle is a little harder to find but it is available [here](https://lcsc.com/product-detail/Wire-To-Board-Wire-To-Wire-Connector_BOOMELE-Boom-Precision-Elec-XH-3AWB_C141812.html) and the vertical [here](https://lcsc.com/product-detail/Wire-To-Board-Wire-To-Wire-Connector_BOOMELE-Boom-Precision-Elec-XH-3AW_C18428.html)

The right angle JST XH doesn't seem to be on KiCAD

**Comment by G-Pereira** [comment]
The vertical SMD JST-XH is a Shenzhen special! JST itself doesn't have it

**Comment by G-Pereira** [comment]
Added!
